language: node_js
deploy:
  provider: heroku
  app: inclusion-app-manager
  api_key:
    secure: vaOLKIH1Ai9OMgNxaOMCADpU4TOFxtY7m3Sj4EcoMcVZx0MGRkBKcN1fuoHWNUNNCVWJaP6fbzOAOQRubhKgX7Mnbgr7QhDT7th3qQM7SI3SdwCLz8oJxgb4BYAI7/KOv5z4i+A8uV66QyeAPWLgHP/+o9H+3tRgtRzf6sFUnqF11hB1CuM8ye6OIa1BeXiiAK0vMuiSJHO5ZeVRUMDPaoZUZrJRVmQlD2M5q2AmIA4pdnnTbWeflzJiwMttNWEhnQHuEdKBDXEZ6WjyLO2BoaqprdD1p1/kMb3iopZFx69A0PgBZRNuC2HAlJRNOcPXhNHD61pLCJuAWGiCidUEtG28k5ZpawFGGBMZysZn4KHSzuUQH8cICsd47724SdrJ5KhMhas8+9F9q5zqyeqfiosKp251hmH04+pJgmxj8PHXHo1aCeVrVE0uJEn8QJeIZuMGXdhdrqlZrjyNxFQPzgOoc5+3jEJoOlV9Qnb89YsrcmVh4zMTTZ3VxithQHIPIr9/LkAT2Fx6mbqpogUEN7b1653j7NkmQu8Ow9XEX340gSrtFdDgcLRYvrsAGTWC5qRNTcFjYS5Q4EFSALpMz9WeW1fqoYIJ1SiJO9p93P8zmf7zSIH8tJBm1lCBQNZ/m0du1WPrsWBafw3sYsSot+pV/MWhygbgCtWBZaFeB18=
